import { createContext, useContext, useState, useEffect, useCallback, type ReactNode } from 'react';
import { api } from './api';
import { useAuth } from './auth';

// ─── Design tokens ────────────────────────────────────────────────────────────
// Every editable token maps to a CSS custom property consumed by index.css.

export interface ThemeSettings {
  vars: Record<string, string>;
  workspaceName: string;
  markLetter: string;
  baseFontSize: number;
  guidelines: Record<string, string>;
}

// Editable knowledge-base sections. Defaults follow the three-tier token model
// (W3C Design Tokens 2025.10) and single-action-accent principle.
export const GUIDELINE_SECTIONS: { key: string; title: string }[] = [
  { key: 'brand',      title: 'Brand & Voice' },
  { key: 'colorUsage', title: 'Color Usage Rules' },
  { key: 'typography', title: 'Typography Rules' },
  { key: 'logo',       title: 'Logo & Mark' },
  { key: 'imagery',    title: 'Imagery & Creatives' },
];

export const DEFAULT_GUIDELINES: Record<string, string> = {
  brand: `Voice: "Trusted Clarity" (Acefone Brand Voice System v1.0). A senior operator who has seen the inside of a contact center — warm enough that a CX manager trusts us, authoritative enough that a VP takes us to their board. HubSpot warmth × Salesforce authority.

Archetype: Empathetic Partner + Intelligent Simplifier. Lead with the reader's reality, translate features into decisions and outcomes. Every claim backed by data or specifics. No jargon, no hype.

Full guide: acefone-design-system/project/uploads/acefone-brand-voice.md`,
  colorUsage: `Source of truth: acefone-design-system/project/colors_and_type.css (full ramps).

- PRIMARY is Acefone Blue #083DDE (blue-600, sampled from logo) — the workhorse for actions and emphasis.
- Green #00AB40 is used SPARINGLY: success, positive stats, confirm CTAs. Never decoratively.
- Body text sits on Dark Blue #051441 (blue-950), not black.
- Neutrals are cool grays biased toward brand blue (gray-50 → gray-900).
- Semantic: success=green-500, warning=#F5A524, danger=#E5484D, info=blue-500. Status colors are reserved for status.
- Token tiers (W3C model): primitives (the ramps) → semantic roles (edited here) → components.`,
  typography: `Primary typeface: Poppins (300–800, self-hosted). Fallback stack matches Poppins geometry.

Scale (1.200 ratio): xs 12 / sm 14 / base 16 / md 18 / lg 20 / xl 24 / 2xl 30 / 3xl 38 / 4xl 48+. In-app UI runs dense at sm(14) base.
Headings: bold/semibold, tight leading (1.1–1.25), Dark Blue #051441. Body: regular, relaxed leading (1.5–1.65).
Eyebrows: 12px caps, +0.08em tracking, blue-600. Mono for identifiers, costs, code.`,
  logo: `Assets: acefone-design-system/project/assets/ (logo.png, logo-mark.svg).

The in-app rail badge shows the mark letter (accent-colored on dark). Keep 1–2 characters. Workspace name appears in the sidebar header and top pill — set both from Branding above, never hardcode in features.`,
  imagery: `LinkedIn/social creatives are generated by the linkedin-creatives agent, which reads the CURRENT brand colors from this design system automatically.

Creative rules: landscape 3:2, max 8 words of in-image text, no fake UI screenshots, no closeup faces, modern flat B2B SaaS aesthetic. Brand gradients available: primary (135deg #1A4ADB→#1338A4), deep, accent green (#00B060→#007540).`,
};

// Defaults = Acefone Design System (acefone-design-system/ in this repo).
export const DEFAULT_THEME: ThemeSettings = {
  vars: {
    '--sn-top':       '#051441',   // ace-blue-950
    '--sn-rail':      '#0A2080',   // ace-blue-900
    '--sn-bg':        '#F7F8FB',   // ace-gray-50
    '--sn-panel':     '#ffffff',
    '--sn-border':    '#DDE1EB',   // ace-gray-200
    '--sn-text':      '#051441',   // ace-fg
    '--sn-muted':     '#4D5570',   // ace-gray-600
    '--sn-link':      '#1E4AE2',   // ace-blue-500
    '--sn-accent':    '#083DDE',   // ace-blue-600 — PRIMARY (logo)
    '--sn-green':     '#00AB40',   // ace-green-500 (logo accent)
    '--sn-blue':      '#1E4AE2',   // ace-info
    '--sn-orange':    '#9C6500',   // ace-warning darkened for text contrast
    '--sn-red':       '#E5484D',   // ace-danger
    '--sn-radius':    '4px',       // ace-radius-xs
    '--sn-radius-lg': '10px',      // ace-radius-md
    '--sn-font':      '"Poppins","Inter",system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif',
    '--sn-mono':      'ui-monospace,"SF Mono","JetBrains Mono",Menlo,Consolas,monospace',
  },
  workspaceName: 'Marketing Intelligence OS',
  markLetter: 'a',
  baseFontSize: 14,
  guidelines: DEFAULT_GUIDELINES,
};

export interface TokenDef { cssVar: string; label: string; type: 'color' | 'font' | 'radius'; }
export interface TokenGroup { title: string; tokens: TokenDef[]; }

export const TOKEN_GROUPS: TokenGroup[] = [
  {
    title: 'Brand',
    tokens: [
      { cssVar: '--sn-accent', label: 'Primary action (buttons)', type: 'color' },
      { cssVar: '--sn-green',  label: 'Accent / live indicators', type: 'color' },
      { cssVar: '--sn-top',    label: 'Header bar',               type: 'color' },
      { cssVar: '--sn-rail',   label: 'Left rail',                type: 'color' },
      { cssVar: '--sn-link',   label: 'Links',                    type: 'color' },
    ],
  },
  {
    title: 'Surfaces',
    tokens: [
      { cssVar: '--sn-bg',     label: 'Page background', type: 'color' },
      { cssVar: '--sn-panel',  label: 'Cards / panels',  type: 'color' },
      { cssVar: '--sn-border', label: 'Borders',         type: 'color' },
    ],
  },
  {
    title: 'Text',
    tokens: [
      { cssVar: '--sn-text',  label: 'Body text',  type: 'color' },
      { cssVar: '--sn-muted', label: 'Muted text', type: 'color' },
    ],
  },
  {
    title: 'Status colors',
    tokens: [
      { cssVar: '--sn-blue',   label: 'Processing / info', type: 'color' },
      { cssVar: '--sn-orange', label: 'Pending / warning', type: 'color' },
      { cssVar: '--sn-red',    label: 'Error / danger',    type: 'color' },
    ],
  },
  {
    title: 'Shape',
    tokens: [
      { cssVar: '--sn-radius',    label: 'Corner radius (controls)', type: 'radius' },
      { cssVar: '--sn-radius-lg', label: 'Corner radius (cards)',    type: 'radius' },
    ],
  },
];

// Poppins is bundled (self-hosted); other options are system-safe stacks —
// nginx CSP blocks external font CDNs.
export const FONT_OPTIONS = [
  { label: 'Poppins (Acefone default)', value: '"Poppins","Inter",system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif' },
  { label: 'Segoe UI',                  value: '"Segoe UI",Roboto,Arial,sans-serif' },
  { label: 'System UI',                 value: 'system-ui,-apple-system,"Segoe UI",Roboto,sans-serif' },
  { label: 'Verdana',                   value: 'Verdana,Geneva,sans-serif' },
  { label: 'Trebuchet MS',              value: '"Trebuchet MS",Helvetica,sans-serif' },
  { label: 'Georgia (serif)',           value: 'Georgia,"Times New Roman",serif' },
];

export const MONO_FONT_OPTIONS = [
  { label: 'System mono (Acefone default)', value: 'ui-monospace,"SF Mono","JetBrains Mono",Menlo,Consolas,monospace' },
  { label: 'Consolas',                      value: 'Consolas,"Courier New",monospace' },
  { label: 'Courier New',                   value: '"Courier New",Courier,monospace' },
];

export function applyTheme(theme: ThemeSettings): void {
  const root = document.documentElement;
  for (const [cssVar, value] of Object.entries(theme.vars)) {
    root.style.setProperty(cssVar, value);
  }
  document.body.style.fontSize = `${theme.baseFontSize}px`;
}

export function mergeTheme(saved: Partial<ThemeSettings> | null): ThemeSettings {
  if (!saved) return DEFAULT_THEME;
  return {
    vars: { ...DEFAULT_THEME.vars, ...(saved.vars ?? {}) },
    workspaceName: saved.workspaceName || DEFAULT_THEME.workspaceName,
    markLetter: (saved.markLetter || DEFAULT_THEME.markLetter).slice(0, 2),
    baseFontSize: saved.baseFontSize || DEFAULT_THEME.baseFontSize,
    guidelines: { ...DEFAULT_GUIDELINES, ...(saved.guidelines ?? {}) },
  };
}

// ─── Export formats — "usable everywhere" ────────────────────────────────────

export function exportAsCss(theme: ThemeSettings): string {
  const lines = Object.entries(theme.vars).map(([k, v]) => `  ${k}: ${v};`);
  return `:root {\n${lines.join('\n')}\n}\nbody { font-size: ${theme.baseFontSize}px; }`;
}

// W3C Design Tokens Community Group format (2025.10)
export function exportAsW3cTokens(theme: ThemeSettings): string {
  const v = theme.vars;
  const color = (val: string) => ({ $type: 'color', $value: val });
  const dim   = (val: string) => ({ $type: 'dimension', $value: val });
  const tokens = {
    color: {
      brand: {
        'primary-action': color(v['--sn-accent']),
        'accent':         color(v['--sn-green']),
        'header':         color(v['--sn-top']),
        'rail':           color(v['--sn-rail']),
        'link':           color(v['--sn-link']),
      },
      surface: {
        'background': color(v['--sn-bg']),
        'panel':      color(v['--sn-panel']),
        'border':     color(v['--sn-border']),
      },
      text: {
        'body':  color(v['--sn-text']),
        'muted': color(v['--sn-muted']),
      },
      status: {
        'info':    color(v['--sn-blue']),
        'warning': color(v['--sn-orange']),
        'danger':  color(v['--sn-red']),
        'success': color(v['--sn-green']),
      },
    },
    dimension: {
      'radius-control': dim(v['--sn-radius']),
      'radius-card':    dim(v['--sn-radius-lg']),
      'font-size-base': dim(`${theme.baseFontSize}px`),
    },
    fontFamily: {
      'sans': { $type: 'fontFamily', $value: v['--sn-font'] },
      'mono': { $type: 'fontFamily', $value: v['--sn-mono'] },
    },
  };
  return JSON.stringify(tokens, null, 2);
}

export function exportAsTailwind(theme: ThemeSettings): string {
  const v = theme.vars;
  return `// tailwind.config — theme.extend
{
  colors: {
    brand: {
      DEFAULT: '${v['--sn-accent']}',
      accent:  '${v['--sn-green']}',
      header:  '${v['--sn-top']}',
      link:    '${v['--sn-link']}',
    },
    surface: {
      DEFAULT: '${v['--sn-panel']}',
      muted:   '${v['--sn-bg']}',
      border:  '${v['--sn-border']}',
    },
    status: {
      info:    '${v['--sn-blue']}',
      warning: '${v['--sn-orange']}',
      danger:  '${v['--sn-red']}',
      success: '${v['--sn-green']}',
    },
  },
  borderRadius: { control: '${v['--sn-radius']}', card: '${v['--sn-radius-lg']}' },
  fontFamily: {
    sans: [${v['--sn-font']}],
    mono: [${v['--sn-mono']}],
  },
}`;
}

// ─── Provider ────────────────────────────────────────────────────────────────

interface ThemeCtx {
  theme: ThemeSettings;
  setThemeLocal: (t: ThemeSettings) => void;   // live preview, not persisted
  reload: () => Promise<void>;
}

const Ctx = createContext<ThemeCtx>({
  theme: DEFAULT_THEME,
  setThemeLocal: () => {},
  reload: async () => {},
});

export function ThemeProvider({ children }: { children: ReactNode }) {
  const { user } = useAuth();
  const [theme, setTheme] = useState<ThemeSettings>(DEFAULT_THEME);

  const reload = useCallback(async () => {
    try {
      const { theme: saved } = await api.getThemeSettings();
      const merged = mergeTheme(saved as Partial<ThemeSettings> | null);
      setTheme(merged);
      applyTheme(merged);
    } catch { /* keep current theme on failure */ }
  }, []);

  useEffect(() => {
    if (user) void reload();
  }, [user, reload]);

  const setThemeLocal = useCallback((t: ThemeSettings) => {
    setTheme(t);
    applyTheme(t);
  }, []);

  return <Ctx.Provider value={{ theme, setThemeLocal, reload }}>{children}</Ctx.Provider>;
}

export function useTheme() {
  return useContext(Ctx);
}
